version: "3.3"
services:
  app:
    build:
        context: .
        dockerfile: ./docker/Dockerfile
    container_name: project_management_app
    ports:
    - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3006
    volumes:
    - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql